Iter13
VOTONO/go-metrics pull request #16
Opened 2024-08-16 07:55 UTC by VOTONO

2024-08-19 06:08 UTC, VOTONO commented on internal/agent/network/metric_sender.go
> +	defer resp.Body.Close()
Добавил обработку

2024-08-19 06:08 UTC, VOTONO commented on internal/agent/network/metric_sender.go
> +func (sender *MetricSenderImpl) sendSingle(metric models.Metric) error {
Убрал

2024-08-19 06:09 UTC, VOTONO commented on internal/server/handlers/value_handler.go
> +	var err error
Ошибся. Исправил логику, теперь сохраняю туда ошибку

2024-08-21 05:50 UTC, VOTONO commented on internal/agent/network/metric_sender.go
> +	defer func() {
Хмм. Я думал все деферы кладутся в стэк и отрабатывают при любом раскладе
Вот тут в документации дефер тоже указан после возвращения ошибки. Или это сделано потому что нет смысла закрывать файл после ошибки, тк он и не был открыт?
https://go.dev/blog/defer-panic-and-recove

```
func CopyFile(dstName, srcName string) (written int64, err error) {
    src, err := os.Open(srcName)
    if err != nil {
        return
    }
    defer src.Close()

    dst, err := os.Create(dstName)
    if err != nil {
        return
    }
    defer dst.Close()

    return io.Copy(dst, src)
}
```

2024-08-21 07:08 UTC, VOTONO commented on internal/agent/network/metric_sender.go
> +	defer func() {
Хмм. Я думал все деферы кладуться в стек при любом раскладе. В примере из документации дефер тоже указан после возвращения ошибки


```
func CopyFile(dstName, srcName string) (written int64, err error) {
    src, err := os.Open(srcName)
    if err != nil {
        return
    }
    defer src.Close()

    dst, err := os.Create(dstName)
    if err != nil {
        return
    }
    defer dst.Close()

    return io.Copy(dst, src)
}
```

2024-08-26 06:17 UTC, nburunova requested changes

2024-08-26 06:17 UTC, nburunova commented on internal/server/repo/postgres_metric_storer.go
> +		switch metric.MType {
тут кот совпадает со StoreSingle. Возможно ли передлать код так, чтобы StoreSingle и StoreSlice переиспользовали код? Например, вызывали одну и ту же фукнцию?
Потому что сейчас, чтобы внести изменения в сохранение метрики, например, если захотим добавить еще один тим метрик, то нужно будет внести изменения  и в StoreSingle и в StoreSlice. Есть вероятность, что внесем изменения в одну функцию и забудем внести в другую. Было бы лучше, если бы было только одно место (одна функция), которую нужно изменить

2024-08-26 06:17 UTC, nburunova commented on internal/server/handlers/batchUpdateHandler.go
> +package handlers
нейминг файла отличается от других в папке, переименуем в batch_update_handler?

2024-08-26 06:17 UTC, nburunova commented on internal/server/handlers/batchUpdateHandler.go
> +		var pgErr *pgconn.PgError
а если сервер у нас запущен в режиме работы с файлом, а не с БД? тогда StoreSlice вернет другую ошибку, не pgErr

2024-08-27 02:51 UTC, VOTONO commented on internal/server/repo/postgres_metric_storer.go
> +			if !errors.Is(scanErr, sql.ErrNoRows) {
Поправил

2024-08-27 04:03 UTC, VOTONO commented on internal/server/repo/postgres_metric_storer.go
> +			tx.Rollback()
Поменял логику, вынес общую логику в отдельные функции

2024-08-27 04:04 UTC, VOTONO commented on internal/server/handlers/batchUpdateHandler.go
> +		var pgErr *pgconn.PgError
Это по техзаданию. в 13 инкременте нужно поймать именно эту ошибку

2024-08-27 06:57 UTC, nburunova commented on internal/server/handlers/batchUpdateHandler.go
> +		var pgErr *pgconn.PgError
По заданию:
Добавьте обработку retriable-ошибок.
Примеры retriable-ошибок:
Ошибка связи с сервером при отправке запроса. 
Ошибка чтения данных из сети или БД из-за проблем соединения. - это ты сделал
Ошибка доступа к файлу, который был заблокирован другим процессом. - это нужно сделать

Иначе получается разное поведение сервера: если сервер работает на БД, то retry срабатывает, а если на файле - то механизма retry нет.
Получается, что сервер на файле более хрупкий, и это не очевидно. А поведение приложения должно быть максимально очевидным и однообразным для всех конфигураций.

2024-08-27 06:58 UTC, nburunova approved these changes

2024-08-27 15:33 UTC, VOTONO commented on internal/server/handlers/batchUpdateHandler.go
> +		var pgErr *pgconn.PgError
Точно, я был невнимателен... Добавил:
`isFileBusyError := errors.As(err, &pathErr) && errors.Is(pathErr.Err, syscall.EBUSY)`
Это оно?

2024-08-28 08:16 UTC, nburunova approved these changes

2024-08-28 08:17 UTC, nburunova commented on internal/server/handlers/batchUpdateHandler.go
> +		var pgErr *pgconn.PgError
да, подойдет :)

2024-08-28 10:16 UTC, merged