Iter15
VOTONO/go-metrics pull request #18
Opened 2024-08-29 03:20 UTC by VOTONO

2024-08-30 13:47 UTC, nburunova requested changes

2024-08-31 01:22 UTC, VOTONO commented on internal/agent/workers/send.go
> +	close(w.stopChannel)
Точно! Добавил wait group

2024-08-31 01:25 UTC, VOTONO commented on internal/auth/hash_signer.go
> +				Body:           &bytes.Buffer{},
Хмм... Это я упустил. Странно что автотесты это не проверяют.
Я попроавил, но не уверен правильно ли. Почему то совсем неинтуитивно для меня

2024-09-02 07:58 UTC, nburunova approved these changes

2024-09-02 07:58 UTC, nburunova commented on internal/auth/hash_signer.go
> +				Body:           &bytes.Buffer{},
а ты  запускал локально? Работает?

2024-09-02 10:40 UTC, merged